In [ ]:
import numpy as np
# shape
    # SupportsIndex: int, tuple, list
    # 1D: 2, (2,), [2]
    # 2D: tuple -> (5,1), (2,5) list -> [4,2], [6,1]
    # 3D: tuple -> (3, 2, 4), (6, 3, 3) list -> [2, 3, 4], [5, 6, 2]
    # multi-dimensions -> tuple -> (2, 4, 5, ....), list -> [4, 6, 3, ....]
    # 2D, 3D, multi -> last value is array item count -> (2,3) = [[0 0 0] [0 0 0]] [3, 2, 2] -> [[[0 0] [0 0]] [[0 0] [0 0]] [[0 0] [0 0]]] 
# dtype
    # int_, int8, int16, int32, int64 -> [4, -3, 0, 6, -45]
    # float16, float32, float64, float128 -> [-49.0, 87.3, 7.9, -9.8]
    # uint, uint8, uint16, uint32, uint64, uintp, uintc (unsigned integer) -> [9, 89, 6, 54, 56, 34]
    # bool, bool_ -> change to [True, False]
        # ex: array[50, "45", 0, "!", "", " ", None, "None", np.nan, True, False, "Hello", "0", "1", -4, 70.0, 0.0, 1.0]
        # output: [True, True, False, True, False, True, False, True, True, True, False, True, True, True, True, True, False, False]
    # str_ or <U{length} ex: "<U5", "<U7"
    # object_

In [3]:
# create array 1D, 2D, 3D, etc..,
arr = np.array([234, 567, 2424,123]) # 1D
print('Dim:', arr.ndim, 'Shape:', arr.shape)
print(arr, "\n")

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Dim:', arr.ndim, 'Shape:', arr.shape)
print(arr, "\n")

arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]]])
print('Dim:', arr.ndim, 'Shape:', arr.shape)
print(arr, "\n")


Dim: 1 Shape: (4,)
[ 234  567 2424  123] 

Dim: 2 Shape: (2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

Dim: 3 Shape: (1, 2, 5)
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]] 



In [ ]:
# create zeros matrix
print(np.array([0, "", None, False, 0.0], dtype=np.bool_))


[False False False False False  True]
