In [39]:
import numpy as np
def output(arr):
    print("--------")
    print('array ->',arr)
    print('dim   ->', arr.ndim)
    print('dtype ->', arr.dtype)
    print('shape ->', arr.shape)
    print('size  ->', arr.size)
    print("--------")

In [40]:
# create 0D (Scalar) array
arr = np.array(5)
print("Ouput 1:")
output(arr)

arr = np.array((2.5))
print("Ouput 2:")
output(arr)

arr = np.array("Hello")
print("Ouput 3:")
output(arr)

arr = np.array((True))
print("Ouput 4:")
output(arr)

Ouput 1:
--------
array -> 5
dim   -> 0
dtype -> int64
shape -> ()
size  -> 1
--------
Ouput 2:
--------
array -> 2.5
dim   -> 0
dtype -> float64
shape -> ()
size  -> 1
--------
Ouput 3:
--------
array -> Hello
dim   -> 0
dtype -> <U5
shape -> ()
size  -> 1
--------
Ouput 4:
--------
array -> True
dim   -> 0
dtype -> bool
shape -> ()
size  -> 1
--------


In [41]:
# change dtype
arr = np.array(3, dtype=np.int64)
print("Before:", arr.dtype)
arr = arr.astype(np.str_)
print("After:", arr.dtype)
print("-"*50)
arr = np.array("Hello")
print("Before:", arr.dtype)
arr = arr.astype(np.bool_)
print("After:", arr.dtype)
print("-"*50)
arr = np.array(True)
print("Before:", arr.dtype)
arr = arr.astype(np.int64)
print("After:", arr.dtype)
print("-"*50)
arr = np.array("6.2")
print("Before:", arr.dtype)
arr = arr.astype(np.float64)
print("After:", arr.dtype)

Before: int64
After: <U21
--------------------------------------------------
Before: <U5
After: bool
--------------------------------------------------
Before: bool
After: int64
--------------------------------------------------
Before: <U3
After: float64


In [42]:
# arithmetic operation (+, -, *, %, /, //)
# supported dtypes: int, float, uint
# True = 1, False = 0

print("Arithmetic Operation")
print("-"*30)

arr1 = np.array(5)
arr2 = np.array(2)
arr3 = np.array("Hello")
arr4 = np.array('hello')
print("Addition        :", arr1 + arr2)
print("Subtraction     :", arr1 - arr2)
print("Multipilication :", arr1 * arr2)
print("Modules         :", arr1 % arr2)
print("Divition        :", arr1 / arr2)
print("Floor           :", arr1 // arr2)

Arithmetic Operation
------------------------------
Addition        : 7
Subtraction     : 3
Multipilication : 10
Modules         : 1
Divition        : 2.5
Floor           : 2


In [43]:
# comparison operation (==, !=, >, <, <=, >=)
# 0 == 0.0 == False -> True
# 1 == 1.0 == True  -> True
print("-"*30)
print("Comparison Operation")
print("-"*30)
print(f'{arr3} == {arr4} :', arr3 == arr4)
print(f'{arr3} != {arr4} :', arr3 != arr4)
print(f'{arr1} > {arr2}          :', arr1 > arr2)
print(f'{arr1} < {arr2}          :', arr1 < arr2)
print(f'{arr1} >= {arr2}         :', arr1 >= arr2)
print(f'{arr1} <= {arr2}         :', arr1 <= arr2)

------------------------------
Comparison Operation
------------------------------
Hello == hello : False
Hello != hello : True
5 > 2          : True
5 < 2          : False
5 >= 2         : True
5 <= 2         : False


In [44]:
# create 1D array
def output(arr, index = 3):
    print("-"*50)
    print("array        :", arr)
    print(f"index of [{index}] :", arr[index])
    print("dtype        :", arr.dtype)
    print("ndim         :", arr.ndim)
    print("shape        :", arr.shape)
    print("size         :", arr.size)
    print("-"*50)

arr = np.array([1, 2, 3, 4, 5])
print("Ouput 1:")
output(arr, 2)

arr = np.array((6.2, 7.1, 8.0, 9.5, 10.8))
print("Ouput 2:")
output(arr)

arr = np.array(["John", "Allen", "Vishal", "Karan", "Sekar"])
print("Ouput 3:")
output(arr, 4)

arr = np.array((1, 0.8, "Hello", False, None, np.nan))
print("Ouput 4:")
output(arr, 0)

Ouput 1:
--------------------------------------------------
array        : [1 2 3 4 5]
index of [2] : 3
dtype        : int64
ndim         : 1
shape        : (5,)
size         : 5
--------------------------------------------------
Ouput 2:
--------------------------------------------------
array        : [ 6.2  7.1  8.   9.5 10.8]
index of [3] : 9.5
dtype        : float64
ndim         : 1
shape        : (5,)
size         : 5
--------------------------------------------------
Ouput 3:
--------------------------------------------------
array        : ['John' 'Allen' 'Vishal' 'Karan' 'Sekar']
index of [4] : Sekar
dtype        : <U6
ndim         : 1
shape        : (5,)
size         : 5
--------------------------------------------------
Ouput 4:
--------------------------------------------------
array        : [1 0.8 'Hello' False None nan]
index of [0] : 1
dtype        : object
ndim         : 1
shape        : (6,)
size         : 6
--------------------------------------------------


In [45]:
# arithmetic operation (+, -, *, %, /, //)
# supported dtypes: int, float, uint
# True = 1, False = 0

print("Arithmetic Operation")
print("-"*30)

arr1 = np.array([6, False, 7])
arr2 = np.array([1, 4.4, True])
print("Addition        :", arr1 + arr2)
print("Subtraction     :", arr1 - arr2)
print("Multipilication :", arr1 * arr2)
print("Modules         :", arr1 % arr2)
print("Divition        :", arr1 / arr2)
print("Floor           :", arr1 // arr2)
print()
arr1 = np.array([5, 6, 7, 8])
arr2 = np.array([1, 2, 3, 4])
print("Addition        :", arr1 + arr2)
print("Subtraction     :", arr1 - arr2)
print("Multipilication :", arr1 * arr2)
print("Modules         :", arr1 % arr2)
print("Divition        :", arr1 / arr2)
print("Floor           :", arr1 // arr2)

Arithmetic Operation
------------------------------
Addition        : [7.  4.4 8. ]
Subtraction     : [ 5.  -4.4  6. ]
Multipilication : [6. 0. 7.]
Modules         : [0. 0. 0.]
Divition        : [6. 0. 7.]
Floor           : [6. 0. 7.]

Addition        : [ 6  8 10 12]
Subtraction     : [4 4 4 4]
Multipilication : [ 5 12 21 32]
Modules         : [0 0 1 0]
Divition        : [5.         3.         2.33333333 2.        ]
Floor           : [5 3 2 2]


In [46]:
# comparison operation (==, !=, >, <, <=, >=)
# 0 == 0.0 == False -> True
# 1 == 1.0 == True  -> True
arr1 = np.array([1,2,3,4,7,6])
arr2 = np.array([1,2,4,5,5,6])
print(arr1 == arr2)
print(arr1 != arr2)
print(arr1 > arr2)
print(arr1 < arr2)
print(arr1 >= arr2)
print(arr1 <= arr2)
print()
arr1 = np.array(["string",{1,3,4},1.7,False,1])
arr2 = np.array(["string",{1,3,4},1.6,0,True])
print(arr1 == arr2)
print(arr1 != arr2)
print(arr1 > arr2)
print(arr1 < arr2)
print(arr1 >= arr2)
print(arr1 <= arr2)

[ True  True False False False  True]
[False False  True  True  True False]
[False False False False  True False]
[False False  True  True False False]
[ True  True False False  True  True]
[ True  True  True  True False  True]

[ True  True False  True  True]
[False False  True False False]
[False False  True False False]
[False False False False False]
[ True  True  True  True  True]
[ True  True False  True  True]


In [47]:
# create 2D array
def output(arr, parent, child):
    print("------------------------------")
    print('array           :')
    print(arr)
    print(f'index of [{parent}]    :', arr[parent])
    print(f'index of [{parent}][{child}] :', arr[parent][child])
    print('dim             :', arr.ndim)
    print('dtype           :', arr.dtype)
    print('shape           :', arr.shape)
    print('size            :', arr.size)
    print("------------------------------")
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
output(arr, 1, 2)

arr = np.array([[4.5, 6.7],[8.9, 1.2],[2.3, 3.4]])
output(arr, 2, 1)

arr = np.array([[0,0.0,"Hello",None,np.nan,True, {1,3,6,7}],["World","0",False,{5,2,3}, 1, 1.0,{"name": "Josh", "age": 32}]])
output(arr, 1, 6)

------------------------------
array           :
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
index of [1]    : [ 6  7  8  9 10]
index of [1][2] : 8
dim             : 2
dtype           : int64
shape           : (2, 5)
size            : 10
------------------------------
------------------------------
array           :
[[4.5 6.7]
 [8.9 1.2]
 [2.3 3.4]]
index of [2]    : [2.3 3.4]
index of [2][1] : 3.4
dim             : 2
dtype           : float64
shape           : (3, 2)
size            : 6
------------------------------
------------------------------
array           :
[[0 0.0 'Hello' None nan True {1, 3, 6, 7}]
 ['World' '0' False {2, 3, 5} 1 1.0 {'name': 'Josh', 'age': 32}]]
index of [1]    : ['World' '0' False {2, 3, 5} 1 1.0 {'name': 'Josh', 'age': 32}]
index of [1][6] : {'name': 'Josh', 'age': 32}
dim             : 2
dtype           : object
shape           : (2, 7)
size            : 14
------------------------------


In [57]:
# arithmetic operation (+, -, *, %, /, //)
# supported dtypes: int, float, uint
# True = 1, False = 0

arr1 = np.array([[1,2,False,4,5],[6,7,8,9,10]])
arr2 = np.array([[10,5,9,4,8],[3,7,2,6,True]])

print("Addition        :", arr1 + arr2)
print("Subtraction     :", arr1 - arr2)
print("Multipilication :", arr1 * arr2)
print("Modules         :", arr1 % arr2)
print("Divition        :", arr1 / arr2)
print("Floor           :", arr1 // arr2)
print()

Addition        : [[11  7  9  8 13]
 [ 9 14 10 15 11]]
Subtraction     : [[-9 -3 -9  0 -3]
 [ 3  0  6  3  9]]
Multipilication : [[10 10  0 16 40]
 [18 49 16 54 10]]
Modules         : [[1 2 0 0 5]
 [0 0 0 3 0]]
Divition        : [[ 0.1    0.4    0.     1.     0.625]
 [ 2.     1.     4.     1.5   10.   ]]
Floor           : [[ 0  0  0  1  0]
 [ 2  1  4  1 10]]

