In [1]:
import numpy as np
# shape
    # SupportsIndex: int, tuple, list
    # 1D ex: 2, (2,), [2]
    # 2D ex: tuple -> (5,1), (2,5) list -> [4,2], [6,1]
    # 3D ex: tuple -> (3, 2, 4), (6, 3, 3) list -> [2, 3, 4], [5, 6, 2]
    # multi-dimensions ex-> tuple -> (2, 4, 5, ....), list -> [4, 6, 3, ....]
    # 2D, 3D, multi ex -> last value is array item count -> (2,3) = [[0 0 0] [0 0 0]] [3, 2, 2] -> [[[0 0] [0 0]] [[0 0] [0 0]] [[0 0] [0 0]]] 
# dtype
    # int_, int8, int16, int32, int64 -> [4, -3, 0, 6, -45]
    # float16, float32, float64, float128 -> [-49.0, 87.3, 7.9, -9.8]
    # uint, uint8, uint16, uint32, uint64, uintp, uintc (unsigned integer) -> [9, 89, 6, 54, 56, 34]
    # bool, bool_ -> change to [True, False]
        # ex: array[50, "45", 0, "!", "", " ", None, "None", np.nan, True, False, "Hello", "0", "1", -4, 70.0, 0.0, 1.0]
        # output: [True, True, False, True, False, True, False, True, True, True, False, True, True, True, True, True, False, False]
    # str_ or <U{length} ex: "<U5", "<U7"
    # object_

In [3]:
# create array 1D, 2D, 3D, etc..,
arr = np.array([234, 567, 2424,123]) # 1D
print('Dim:', arr.ndim, 'Shape:', arr.shape)
print(arr, "\n")

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Dim:', arr.ndim, 'Shape:', arr.shape)
print(arr, "\n")

arr = np.array([[[1,2,3,4,5],[6,7,8,9,10]]])
print('Dim:', arr.ndim, 'Shape:', arr.shape)
print(arr, "\n")


Dim: 1 Shape: (4,)
[ 234  567 2424  123] 

Dim: 2 Shape: (2, 5)
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

Dim: 3 Shape: (1, 2, 5)
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]] 



In [ ]:
# create zeros matrix
zeros = np.zeros(2)
print(zeros)
zeros = np.zeros((2,5))
print(zeros)
zeros = np.zeros([2, 4, 2])
print(zeros)
zeros = np.zeros([2,3], dtype=np.int_)
print(zeros)
zeros = np.zeros((3, 3, 2, 2), dtype=np.bool_)
print(zeros)


[0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[0 0 0]
 [0 0 0]]
[[[['' '']
   ['' '']]

  [['' '']
   ['' '']]

  [['' '']
   ['' '']]]


 [[['' '']
   ['' '']]

  [['' '']
   ['' '']]

  [['' '']
   ['' '']]]


 [[['' '']
   ['' '']]

  [['' '']
   ['' '']]

  [['' '']
   ['' '']]]]


In [20]:
# create ones matrix
ones = np.ones(5)
print(ones)
ones = np.ones([5, 2])
print(ones)
ones = np.ones((2, 2, 3))
print(ones)
ones = np.ones([3, 4, 2, 2], dtype=np.bool_)
print(ones)
ones = np.ones([3, 4, 2, 2], dtype=np.int_)
print(ones)

[1. 1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
[[[[ True  True]
   [ True  True]]

  [[ True  True]
   [ True  True]]

  [[ True  True]
   [ True  True]]

  [[ True  True]
   [ True  True]]]


 [[[ True  True]
   [ True  True]]

  [[ True  True]
   [ True  True]]

  [[ True  True]
   [ True  True]]

  [[ True  True]
   [ True  True]]]


 [[[ True  True]
   [ True  True]]

  [[ True  True]
   [ True  True]]

  [[ True  True]
   [ True  True]]

  [[ True  True]
   [ True  True]]]]
[[[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]

  [[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]


 [[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]

  [[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]


 [[[1 1]
   [1 1]]

  [[1 1]
   [1 1]]

  [[1 1]
   [1 1]]

  [[1 1]
   [1 1]]]]


In [2]:
# create empty matrix
empty = np.empty(4)
print(empty)
empty = np.empty(2, dtype=np.int_)
print(empty)
empty = np.empty((3, 3), dtype=np.str_)
print(empty)
empty = np.empty([2,10], dtype=np.bool_)
print(empty)

[1.62271603e-315 0.00000000e+000 1.62301545e-315 1.62447812e-315]
[80211     0]
[['' '' '']
 ['' '' '']
 ['' '' '']]
[[ True  True  True False False False False False False False]
 [False False False False False False  True  True  True False]]


In [76]:
# create range array (start, stop, step)
arange = np.arange(4) # array from 0 to 3 (4th excluded)
print(arange)
arange = np.arange(0, 10) # array from 0 to 9 (10th excluded)
print(arange)
arange = np.arange(1, 20, 2) # array from 1 to 19 (20th excluded)( step to every next 2nd value from 1)
print(arange)
arange = np.arange(2, dtype=np.bool_) # bool dtype support int 0 to 2 (error if greater then 2)
print(arange)

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]
[False  True]
